### ISSUE TITLE
Can't see help with a non existing dir flag

### ISSUE THREAD

**Issue by adrianlzt** [alecthomas/kingpin#115]
If a flag is defined like this:
`
name = kingpin.Flag("foo", "foo help").Default("/bar").ExistingDir()
`

When executed it fails because "/bar" dir doesn't exists:
```
$ go run flag_existing.go
flag_existing: error: path '/bar' does not exist, try --help
```
But trying to execute with --help, as suggested, gives the same error:
```
$ go run flag_existing.go --help
flag_existing: error: path '/bar' does not exist, try --help
``` 

Complete example: https://gist.github.com/0954be9b5c2db81d7ddd

**Comment by alecthomas** [comment]
The assumption with default values is that they are always correct. If they are not correct it's considered a programmer error, not a user error (in fact, Kingpin used to panic if default values were not valid). That is partially because help can only be generated if there are default values (as the default values are used to format the help). This obviously falls down somewhat with default values that can fail due to external constraints. It's definitely not ideal, but it's currently not considered a bug.

A workaround for your example is to use `String()`.

I've added a entry to the v3 list to think about how to make this work.
