### ISSUE TITLE
"command help subcommand" also shows global flags

### ISSUE THREAD

**Issue by diatboti** [alecthomas/kingpin#143]
thanks for the package !
I noticed that when using "command help subcommand", it shows also "global" flags of command. This is not as described in the example. 
$chat help post
usage: chat post [<flags>] <channel> [<text>...]

Post a message to a channel.
//here only supposed to show --image
Flags:
  --help              Show context-sensitive help (also try --help-long and --help-man). 
  --debug             Enable debug mode.
  --server=127.0.0.1  Server address.
  --image=IMAGE       Image to post.

Args:
  <channel>  Channel to post to.
  [<text>]   Text to post.

**Comment by alecthomas** [comment]
This is intentional because those flags are applicable in that context. ie. flags from any preceding "scope" can be used.

That said, it is not clear which flags are from which scope, so in the next major revision these flags will be grouped in the help (see #90 to track this feature, among others).
