### ISSUE TITLE
Why double pointers for net.TCPAddr, url.URL, etc?

### ISSUE THREAD

**Issue by mattbostock** [alecthomas/kingpin#200]
Some types such as `net.TCPAddr` and `url.URL` are referenced using double pointers, i.e. `**`.

Examples:
https://github.com/alecthomas/kingpin/blame/bf17db2c43f59ff3d97a39d1feacef18d75eaf95/values.go#L188
https://godoc.org/github.com/alecthomas/kingpin#ArgClause.TCPVar

Is that intentional?

**Comment by alecthomas** [comment]
This is primarily because for these values, a nil pointer represents "not provided", and there is no way to achieve this with the flags approach of returning a pointer to the real value, without using a double pointer.

ie. you can not have `func (a *FlagClause) URL() *url.URL` and support nil values.
