### ISSUE TITLE
Make help less busy by removing angle brackets

### ISSUE THREAD

**Issue by eburnette** [alecthomas/kingpin#39]
Currently help prints text like:

`usage: chat [<flags>] <command> [<flags>] [<args> ...]`

All the angle brackets make it hard to read. I suggest something simpler like:

usage: chat [options] command [command options] [arguments...]

**Comment by alecthomas** [comment]
I'm going to need an example to replicate... Because what you describe is what it should be doing.

**Comment by alecthomas** [comment]
Ah, I see what happened. Github swallowed your `<>` so it looked like `usage: chat [] [] []`.

It's pretty common practice for command line applications to use `<X>` for user-specified values, plus it removes any ambiguity. For example, how would you specify subcommands?

Current:
```
register <nick> <name>
```

Proposed:
```
register nick name
```

That said, I have a partially [complete branch](https://github.com/alecthomas/kingpin/tree/v2-model) which makes the object model public, so that it can be used to generate help [with templates](https://github.com/alecthomas/kingpin/blob/v2-model/usage.go#L86). This would allow users to generate any type of help they prefer by using custom templates.

**Comment by eburnette** [comment]
There's another issue for shortening the help for subcommands. I don't think they should list out their arguments in the top level help.
