### ISSUE TITLE
I want to tell if an option was set

### ISSUE THREAD

**Issue by johnl** [alecthomas/kingpin#61]
I'm using this style of setup:

```
	update := servers.Command("update", "Update a new cloud server").Action(cmd.update)
	update.Arg("identifier", "Identifier of servers to update").Required().StringVar(&cmd.Id)
	update.Flag("name", "New name to give server").Short('n').StringVar(&cmd.Name)
```

But I need to know if the name option was actually provided or not - I can't just check that cmd.Name is empty or not (because the user might be trying to delete the name by providing an empty string).

If I could pass a pointer to a string into StringVar, I could check if it's nil or not, but that's not currently supported.

I could implement my own value type for it I suppose, but it seems like a common requirement - is there a way to do this? If not, should kingpin support it? Should it support the same for all types?

**Comment by alecthomas** [comment]
I think writing your own value implement ration is probably the best option. Adding support would complicate the interface and implementation considerably.

One hackish alternative is to use a default value like "?" that cannot be valid for that value, though this isn't possible in all cases.

**Comment by johnl** [comment]
This is my solution, it seems to work. Does it look reasonable? I thought it might help others with the same problem in future :)

cmd.Name is a *string

```
type pStringValue struct {
	target **string
}

func (ps *pStringValue) Set(s string) error {
	*ps.target = &s
	return nil
}

func (ps *pStringValue) String() string {
	if ps.target != nil && *ps.target != nil {
		return **ps.target
	} else {
		return ""
	}
}

func pStringVar(s kingpin.Settings, target **string) {
	p := new(pStringValue)
	p.target = target
	s.SetValue(p)
}

update := servers.Command("update", "Create a new cloud server").Action(cmd.update)
update.Arg("identifier", "Identifier of servers to update").Required().StringVar(&cmd.Id)
pStringVar(update.Flag("name", "Name to give the new server").Short('n'), &cmd.Name)

**Comment by alecthomas** [comment]
Definitely looks reasonable to me.

**Comment by ches** [comment]
I had the same wish and found this issue. My use case is pretty straightforward I think: I have some options that can either be configured via environment variables, or with flags, e.g. `MYAPP_DEBUG` or `--debug`. I want to give precedence to explicitly-passed flags, but can't currently know whether they were explicitly passed or not.

A `Bool()` like debug is an example of a case where @alecthomas's quick hack won't work: one can't set an arbitrary sentinel value since it won't parse as a Boolean. I wondered if this was something action callbacks could be used for, I'm trying to grok how they work since they don't seem to have high-level documentation yet. But custom value implementation seems rather the way to go for now, thanks @johnl for sharing an example.

I can understand that first-class support for this might be a major complication, but perhaps this workaround pattern is worthy of FAQ documentation :smile: 

Thanks for the package @alecthomas, it's a pleasure to use.

**Comment by alecthomas** [comment]
For that specific example, Kingpin supports environment variables natively!

**Comment by ches** [comment]
Aha, `OverrideDefaultFromEnvar`, cheers :grin:

**Comment by ripienaar** [comment]
This is especially annoying with booleans:

```go
// OptionalBoolValue is contains a *bool and implements kingpin.Value
type OptionalBoolValue struct {
	val *bool
}

func OptionalBoolean(s kingpin.Settings) *OptionalBoolValue {
	target := &OptionalBoolValue{}
	s.SetValue(target)
	return target
}

func (v *OptionalBoolValue) SetBool(val bool) {
	v.val = &val
}

func (v *OptionalBoolValue) IsSetByUser() bool { return v.val != nil }

func (v *OptionalBoolValue) Value() bool {
	if v.val == nil {
		return false
	}
	return *v.val
}

func (v *OptionalBoolValue) Set(s string) error {
	b, err := strconv.ParseBool(s)
	if err != nil {
		return err
	}
	v.val = &b

	return nil
}

func (v *OptionalBoolValue) String() string {
	if v.val == nil {
		return ""
	}

	return fmt.Sprintf("%v", *v.val)
}

func (v *OptionalBoolValue) IsBoolFlag() bool { return true }
```

Use this like below to get boolean like behaviour - no value and has the --no-optional setting set too:

```go
opt := OptionalBoolean(f.Flag("optional", "Optional flat"))
```
